import folium

class Media:
        icon_url_turtle = 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F464%2F464955.png&f=1&nofb=1'
        icon_url_flood = 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.covervillemedia.com%2Fstatewidesolutions%2Fwp-content%2Fuploads%2F2015%2F06%2Fflood-icon.png&f=1&nofb=1'
        icon_url_glacier = 'https://cdn2.iconfinder.com/data/icons/world-disaster-line-color-climate-change/512/Melting_Glaciers-512.png'


class Descriptions:
        desc_turtle = '<b>Raine Island sea turtles are being born mostly female due to warming.</b> <br><br> Female baby turtles now outnumber males 116 to 1! <br> <br> <a href="Learn More">https://www.nationalgeographic.com/environment/2019/04/sea-turtle-sex-ratio-crisis-from-climate-change-has-hope/</a>'
        desc_flood =  '<b>Climate change helped cause massive floods in Louisiana.</b> <br><br> Climate change increases the intensity of precipitation because warm weather leads more water to evaporate forming wetter clouds. South Louisiana received nearly 30 inches of rain between August 10 and 17. 13 people died in the floods, which inundated Baton Rouge and destroyed 60,000 homes. <br> <br> <a href="Learn More">https://time.com/4482109/climate-change-louisiana-flooding/</a>'
        desc_glacier_sperry =  '<b>Sperry Glacier has shrunk from more than 800 acres (320 hectares) to 100 acres. </b> <br><br> When President Taft created Glacier National Park in 1910, it was home to an estimated 150 glaciers. Since then the number has decreased to fewer than 30, and most of those remaining have shrunk in area by two-thirds. It is predicted that within 30 years most if not all of the park\'s namesake glaciers will disappear. <br> <br> <a href="Learn More">https://www.nationalgeographic.com/environment/global-warming/big-thaw/</a>'
        desc_glacier_mont_blanc_argentiere =  '<b>Research published in 2019 by ETH Zurich, says that 2/3rd of the ice in the glaciers of the Alps is doomed to melt by the end of the century due to climate change </b> <br><br> On Mont Blanc, the Argentière Glacier has receded 1,150 m (3,770 ft) since 1870. <br> <br> <a href="Learn More">https://en.wikipedia.org/wiki/Retreat_of_glaciers_since_1850</a>'
        desc_glacier_mont_blanc_merdeglace =  '<b>Research published in 2019 by ETH Zurich, says that 2/3rd of the ice in the glaciers of the Alps is doomed to melt by the end of the century due to climate change </b> <br><br> On Mont Blanc, Mer de Glace, which is the largest glacier in France at 12 km (7.5 mi) in length, has retreated 500 m (1,600 ft) between 1994 and 2008. The glacier has retreated 2,300 m (7,500 ft) since the end of the Little Ice Age. <br> <br> <a href="Learn More">https://en.wikipedia.org/wiki/Retreat_of_glaciers_since_1850</a>'
        desc_glacier_mont_blanc_bossons    =  '<b>Research published in 2019 by ETH Zurich, says that 2/3rd of the ice in the glaciers of the Alps is doomed to melt by the end of the century due to climate change </b> <br><br> The Bossons Glacier once extended from the summit of Mont Blanc at 4,807 m (15,771 ft) to an elevation of 1,050 m (3,440 ft) in 1900. By 2008 Bossons Glacier had retreated to a point that was 1,400 m (4,600 ft) above sea level. <br> <br> <a href="Learn More">https://en.wikipedia.org/wiki/Retreat_of_glaciers_since_1850</a>'
        desc_glacier_morteratsch           =  '<b>Research published in 2019 by ETH Zurich, says that 2/3rd of the ice in the glaciers of the Alps is doomed to melt by the end of the century due to climate change </b> <br><br> The overall retreat from 1878 to 1998 has been 2 km (1.2 mi) with a mean annual retreat rate of approximately 17 m (56 ft) per year. This long-term average was markedly surpassed in recent years with the glacier receding 30 m (98 ft) per year during the period between 1999–2005.<br> <br> <a href="Learn More">https://en.wikipedia.org/wiki/Retreat_of_glaciers_since_1850</a>'

class Layers:
        layer_fauna     = folium.FeatureGroup(name='Fauna')
        layer_flora     = folium.FeatureGroup(name='Flora')
        layer_ecosystem = folium.FeatureGroup(name='Ecosystem')
        layer_melt      = folium.FeatureGroup(name='Melting Ice')